version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql-cnt
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: credit_card_system_eldar
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database_setup_script.sql:/docker-entrypoint-initdb.d/database_setup_script.sql

volumes:
  mysql-data:
