spring:
  application:
    name: credit-card-system-api
  data:
    jdbc:
      repositories:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/credit_card_system_eldar
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
